site_name: PUEBI – Pedoman Umum Ejaan Bahasa Indonesia
pages:
  - 'Beranda': 'index.md'
  - 'Pemakaian Huruf':
    - 'Huruf Abjad': 'huruf/huruf-abjad.md'
    - 'Huruf Vokal': 'huruf/huruf-vokal.md'
    - 'Huruf Konsonan': 'huruf/huruf-konsonan.md'
    - 'Huruf Diftong': 'huruf/huruf-diftong.md'
    - 'Gabungan Konsonan': 'huruf/gabungan-konsonan.md'
    - 'Huruf Kapital': 'huruf/huruf-kapital.md'
    - 'Huruf Miring': 'huruf/huruf-miring.md'
    - 'Huruf Tebal': 'huruf/huruf-tebal.md'
  - 'Penulisan Kata':
    - 'Kata Dasar': 'kata/dasar.md'
    - 'Kata Berimbuhan': 'kata/temp.md'
    - 'Bentuk Ulang': 'kata/temp.md'
    - 'Gabungan Kata': 'kata/temp.md'
    - 'Pemenggalan Kata': 'kata/temp.md'
    - 'Kata Depan': 'kata/temp.md'
    - 'Partikel': 'kata/temp.md'
    - 'Singkatan dan Akronim': 'kata/temp.md'
    - 'Angka dan Bilangan': 'kata/temp.md'
    - 'Kata Ganti': 'kata/temp.md'
    - 'Kata Sandang': 'kata/temp.md'
  - 'Pemakaian Tanda Baca':
    - 'Tanda Titik (.)': 'tanda-baca/temp.md'
    - 'Tanda Koma (,)': 'tanda-baca/temp.md'
    - 'Tanda Titik Koma (;)': 'tanda-baca/temp.md'
    - 'Tanda Titik Dua (:)': 'tanda-baca/temp.md'
    - 'Tanda Hubung (-)': 'tanda-baca/temp.md'
    - 'Tanda Pisah (—)': 'tanda-baca/temp.md'
    - 'Tanda Tanya (?)': 'tanda-baca/temp.md'
    - 'Tanda Seru (!)': 'tanda-baca/temp.md'
    - 'Tanda Elipsis (…)': 'tanda-baca/temp.md'
    - 'Tanda Petik (''…'')': 'tanda-baca/temp.md'
    - 'Tanda Petik Tunggal ("…")': 'tanda-baca/temp.md'
    - 'Tanda Kurung ((…))': 'tanda-baca/temp.md'
    - 'Tanda Kurung Siku ([…])': 'tanda-baca/temp.md'
    - 'Tanda Garis Miring (/)': 'tanda-baca/temp.md'
    - 'Tanda Penyingkat ('')': 'tanda-baca/temp.md'
  - 'Penulisan Unsur Serapan': 'penulisan-unsur-serapan.md'
theme: 'readthedocs'
repo_name: 'GitHub'
repo_url: 'https://github.com/ivanlanin/puebi'
google_analytics: ['UA-80210173-1', 'auto']
markdown_extensions:
  - admonition